version: '3.8'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: academic_support_system
      MYSQL_USER: root
      MYSQL_PASSWORD: name
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  web:
    build: .
    command: gunicorn --bind 0.0.0.0:5000 app:app
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    environment:
      FLASK_ENV: development
      MYSQL_HOST: localhost
      MYSQL_USER: root
      MYSQL_PASSWORD: name
      MYSQL_DB: academic_support_system

volumes:
  mysql-data:
