services:
  - type: web
    name: joseph-1
    env: docker
    region: oregon
    plan: free
    buildCommand: docker-compose build
    startCommand: docker-compose up
    envVars:
      - key: MYSQL_ROOT_PASSWORD
        value: your_root_password
      - key: MYSQL_DATABASE
        value: academic_support_system
      - key: MYSQL_USER
        value: root
      - key: MYSQL_PASSWORD
        value: name
      - key: FLASK_ENV
        value: development

databases:
  - name: joseph-db
    type: mysql
    region: oregon
    plan: free
    properties:
      - name: MYSQL_DATABASE
        value: academic_support_system
      - name: MYSQL_USER
        value: root
      - name: MYSQL_PASSWORD
        value: name
      - name: MYSQL_ROOT_PASSWORD
        value: your_root_password
